ARG RUBY_VERSION=3.2.2
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim as base

# Rails app lives here
WORKDIR /rails

RUN groupadd -g 2000 app
RUN adduser --disabled-login --shell /sbin/nologin --gid 2000 --uid 2000 app
RUN chown app:app /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential default-libmysqlclient-dev git libvips pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

COPY --chown=app:app Gemfile Gemfile.lock ./
RUN bundle install

CMD ["sh", "-c", "bundle install && rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"]
